s = "hello world"
print(f"1: {s.capitalize()}")
print(f"2: {s.upper()}")
print(f"3: {s.lower()}")
print(f"4: {s.count('o')}")
print(f"5: {s.find('o')}")
print(f"6: {s.center(20, 'z')}")
print("7: {0}".format("hello\thi"))
s = "hello"
print(f"8: {s.isalnum()}")
print(f"9: {s.isalpha()}")
print(f"10: {s.islower()}")
print(f"11: {s.isspace()}")
print(f"12: {s.istitle()}")
print(f"13: {s.isupper()}")
print(f"13.1: {'HELLO'.isupper()}")
print(f"14: {s.endswith('o')}")
print(f"14.1: {s[-1] == 'o'}")
print(f"15: {s.split('e')}")
print(f"16: {s.partition('e')}")
